---
title: "21.05.13_C2bbe1_3'TOPnNet1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(ggpubr)
library(ggridges)

```

## 7 Day differentiated C2bbe1 cells on dishes

```{r,  read in spots}
spots <- as_tibble(read.csv("21.05.13_C2bbe1FISH/Results/_FISH-QUANT__all_spots_210513.txt", header = TRUE, sep = "\t"))

spots <- spots %>% separate(File, into = c("C2bbe1", "7d", "line", "image", "Stack"), sep = "_") %>% mutate(image = substr(image, 1, 2)) %>% select(-C2bbe1, -`7d`, -Stack)

```

```{r, thresholdmyself}
spots %>% mutate(group = ifelse(line == "Lox", "neg", "pos")) %>% select(group, SigmaX, SigmaZ, BGD, Pos_Z) %>% gather(-group,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = group, fill = group)) + geom_density(alpha = 0.5) + facet_wrap(.~param, scales = "free") + theme_cowplot()

#these parameters provide large differences...
spots %>% mutate(group = ifelse(line == "Lox", "neg", "pos")) %>% select(group, AMP, INT_raw, INT_filt) %>% gather(-group,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = group, fill = group)) + geom_density(alpha = 0.5) + facet_wrap(.~param, scales = "free") + theme_cowplot() + ylim(0,2000)

##a closer look with each condition.
spots %>% select(line,INT_raw) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(450,1500) + geom_hline(yintercept = 850)

spots %>% select(line,INT_filt) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(50,1000) + geom_hline(yintercept = 450) + ylim(0,1500)

spots %>% select(line,BGD) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(100,1000) + geom_hline(yintercept = 500)

#really limits spots.
spots_filt <- spots %>% filter(as.numeric(INT_raw) > 850)

```

```{r, spot_analysis}

comparisons <- list(c("pTL005", "Net1UTR"), c("pTL005", "RPL73TOPWT"), c("Net1UTR", "Net1peak"), c("RPL73TOPWT", "RPL73TOPmut"))

spots_filt %>% group_by(line, image, Cell) %>% summarise(num_spots = n()) %>% ggplot(aes(x = line, y = num_spots, fill = line)) + geom_violin() + geom_boxplot(width = 0.25) + geom_point(alpha = 0.01, position = "jitter") + theme_cowplot() + guides(fill = FALSE, col = FALSE) + stat_compare_means(comparisons = comparisons, method = "wilcox.test", label.y = c(275,300,325,250)) + labs(x = "", y = "Number of spots per cell")

spots_filt %>% ggplot(aes(x = line, y = as.numeric(Pos_Z), fill = line)) + geom_point(alpha = 0.1, position = "jitter") + geom_violin() + geom_boxplot(width = 0.25, outlier.shape = NA) + theme_cowplot() + guides(fill = FALSE, col = FALSE) + stat_compare_means(comparisons = comparisons, method = "wilcox.test") + labs(x ="", y = "Raw FISH-quant -Pos_Z")

med_line <- spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-1000) / 1000)) %>% filter(line == "pTL005") %>% summarize(median(Position_In_Z)) %>% as.numeric()

spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-1000) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x = line, y = Position_In_Z, fill = line)) + geom_violin(aes(alpha = line)) + geom_boxplot(aes(alpha = line), width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = FALSE, col = FALSE, alpha = FALSE) + stat_compare_means(comparisons = list(c("pTL005", "Net1UTR"), c("pTL005", "Net1peak"), c("pTL005", "RPL73TOPWT"), c("pTL005", "RPL73TOPmut"), c("Net1UTR", "Net1peak"), c("RPL73TOPWT", "RPL73TOPmut")), method = "wilcox.test", label.y = c(10,11,12,13,10,10)) + geom_hline(yintercept = med_line, size = 1, linetype = "dashed")  + scale_x_discrete(limits = c("pTL005", "Net1UTR", "Net1peak", "RPL73TOPWT", "RPL73TOPmut"), labels = c("Firefly", "Net1\nUTR", "Net1\npeak oligo", "3'TOP\nRPL7 WT", "3'TOP\nRPL7 mut")) + scale_fill_manual(values = c("#2c8bb0", "#2c8bb0", "#808080", "#ff8537", "#ff8537")) + scale_alpha_manual(values = c(0.5,1,1,0.5,1)) + labs(x = "", y = "Position in Z (um)") 

## For plot

spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-1000) / 1000)) %>% filter(line != "Lox", line != "RPL73TOPWT", line != "RPL73TOPmut") %>% ggplot(aes(x = line, y = Position_In_Z, fill = line)) + geom_violin(aes(alpha = line)) + geom_boxplot(aes(alpha = line), width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = FALSE, col = FALSE, alpha = FALSE) + stat_compare_means(comparisons = list(c("pTL005", "Net1UTR"), c("pTL005", "Net1peak"), c("Net1UTR", "Net1peak")), method = "wilcox.test", label.y = c(14,15,13)) + geom_hline(yintercept = med_line, size = 1, linetype = "dashed")  + scale_x_discrete(limits = c("pTL005", "Net1UTR", "Net1peak"), labels = c("Firefly", "Net1\nUTR", "Net1\npeak oligo")) + scale_fill_manual(values = c("#2c8bb0", "#2c8bb0", "#808080")) + scale_alpha_manual(values = c(0.5,1,1)) + labs(x = "", y = "Position in Z (um)") 


```

# 5'TOP data (this is on membranes)

```{r, }
tidy_spot_files <- function(args){ 
  spottext <- read_lines(args[1])
  
  coords <- data.frame("start" = which(grepl(pattern = "SPOTS_START", spottext))+2, 
                       "end" = which(grepl(pattern = "SPOTS_END", spottext))-1,
                       "cell" = c(1:length(which(grepl(pattern = "SPOTS_START", spottext))+2)))
  
  x <- c(1:nrow(coords))
  cell_spot_list <- lapply(x, function(x){tidy_cell_spots(spottext, coords$start[x], coords$end[x], coords$cell[x])})
  
  cell_spots <- do.call(rbind, cell_spot_list) %>% mutate(gene = args[3], day = args[2], image = args[4]) %>% select(gene, day, image, cell, everything())

}


tidy_cell_spots <- function(spottext, start, end, cell) {
  spottext[start:end] %>% 
    as_tibble() %>% 
    separate(value, into = c("Pos_Y", "Pos_X", "Pos_Z", "AMP", "BGD", "RES", "SigmaX", "SigmaY", "SigmaZ", "Cent_Y", "Cent_X", "Cent_Z", "MuY", "MuX", "MuZ", "ITERY_det", "Y_det", "X_det", "Z_det", "Y_min", "Y_max", "X_min", "X_max", "Z_min", "Z_max", "INT_raw", "INT_filt", "SC_det", "SC_det_norm", "TH_det", "TH_fit", "IN_nuc"), sep = "\t") %>% 
    mutate(cell = cell)
}

spot_files_7d <- list(c("RP_7d/Results/7d_005_01_#2_STACK__outline_spots_200726.txt", "7", "FF", "01"),
              c("RP_7d/Results/7d_005_02_#2_STACK__outline_spots_200726.txt", "7", "FF", "02"),
              c("RP_7d/Results/7d_005_03_#2_STACK__outline_spots_200726.txt", "7", "FF", "03"),
              c("RP_7d/Results/7d_Lox_01_#2_STACK__outline_spots_200726.txt", "7", "Lox", "01"),
              c("RP_7d/Results/7d_Lox_02_#2_STACK__outline_spots_200726.txt", "7", "Lox", "02"),
              c("RP_7d/Results/7d_Lox_03_#2_STACK__outline_spots_200726.txt", "7", "Lox", "03"),
              c("RP_7d/Results/7d_RPL7_01_#2_STACK__outline_spots_200726.txt", "7", "RPL7", "01"),
              c("RP_7d/Results/7d_RPL7_02_#2_STACK__outline_spots_200726.txt", "7", "RPL7", "02"),
              c("RP_7d/Results/7d_RPL7_03_#2_STACK__outline_spots_200726.txt", "7", "RPL7", "03"),
              c("RP_7d/Results/7d_RPL8_01_#2_STACK__outline_spots_200726.txt", "7", "RPL8", "01"),
              c("RP_7d/Results/7d_RPL8_02_#2_STACK__outline_spots_200726.txt", "7", "RPL8", "02"),
              c("RP_7d/Results/7d_RPL8_03_#2_STACK__outline_spots_200726.txt", "7", "RPL8", "03"),
              c("RP_7d/Results/7d_RPS28_01_#2_STACK__outline_spots_200726.txt", "7", "RPS28", "01"),
              c("RP_7d/Results/7d_RPS28_02_#2_STACK__outline_spots_200726.txt", "7", "RPS28", "02"),
              c("RP_7d/Results/7d_RPS28_03_#2_STACK__outline_spots_200726.txt", "7", "RPS28", "03"))

x <- c(1:length(spot_files_7d))
cell_file_list_7d <- lapply(x, function(x){tidy_spot_files(unlist(spot_files_7d[x]))})
spots_7d <- do.call(rbind, cell_file_list_7d) 

spot_files_7dM <- list(c("20.11.14_7d_RPwMut/Results/7d_RP7mut_02_#2_STACK__outline_spots_201114.txt", "7M", "RPL7mut", "02"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP7mut_03_#2_STACK__outline_spots_201114.txt", "7M", "RPL7mut", "03"),
                       #c("20.11.14_7d_RPwMut/Results/7d_RP28_01_#2_STACK__outline_spots_201114.txt", "7M", "RPS28", "01"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP28_02_#2_STACK__outline_spots_201114.txt", "7M", "RPS28", "02"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP28_03_#2_STACK__outline_spots_201114.txt", "7M", "RPS28", "03"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP28mut_01_#2_STACK__outline_spots_201114.txt", "7M", "RPS28mut", "01"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP28mut_02_#2_STACK__outline_spots_201114.txt", "7M", "RPS28mut", "02"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP28mut_03_#2_STACK__outline_spots_201114.txt", "7M", "RPS28mut", "03"),
                       c("20.11.14_7d_RPwMut/Results/7d_FF_01_#2_STACK__outline_spots_201114.txt", "7M", "FF", "01"),
                       c("20.11.14_7d_RPwMut/Results/7d_FF_02_#2_STACK__outline_spots_201114.txt", "7M", "FF", "02"),
                       c("20.11.14_7d_RPwMut/Results/7d_Lox_01_#2_STACK__outline_spots_201114.txt", "7M", "Lox", "01"),
                       c("20.11.14_7d_RPwMut/Results/7d_Lox_02_#2_STACK__outline_spots_201114.txt", "7M", "Lox", "02"),
                       c("20.11.14_7d_RPwMut/Results/7d_Lox_03_#2_STACK__outline_spots_201114.txt", "7M", "Lox", "03"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP7_01_#2_STACK__outline_spots_201114.txt", "7M", "RPL7", "01"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP7_02_#2_STACK__outline_spots_201114.txt", "7M", "RPL7", "02"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP7_03_#2_STACK__outline_spots_201114.txt", "7M", "RPL7", "03"),
                       c("20.11.14_7d_RPwMut/Results/7d_RP7mut_01_#2_STACK__outline_spots_201114.txt", "7M", "RPL7mut", "01"))

x <- c(1:length(spot_files_7dM))
cell_file_list_7dM <- lapply(x, function(x){tidy_spot_files(unlist(spot_files_7dM[x]))})
spots_7dM <- do.call(rbind, cell_file_list_7dM) 

try <- rbind(spots_7d, spots_7dM) %>% filter(as.numeric(INT_raw) > 1650, as.numeric(SigmaX) < 140, as.numeric(SigmaZ) < 600, as.numeric(BGD) < 1100, as.numeric(BGD) > 865)

try %>% filter(gene != "RPL8") %>% group_by(gene, image, cell) %>% summarise(num_spots = n()) %>% ggplot(aes(x = gene, y = num_spots, fill = gene, alpha = gene)) + geom_violin() + geom_boxplot(width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.01, position = "jitter") + theme_cowplot() + guides(fill = FALSE, alpha = FALSE) + labs(x = "", y = "Number of spots per cell") + EnvStats::stat_n_text(y.pos = -25) + coord_cartesian(ylim = c(-25,200)) + scale_fill_manual(values = c("#808080", "#808080","#e8c040", "#e8c040", "#b82080", "#b82080")) + scale_alpha_manual(values = c(1,1,1,0.25,1,0.25)) + scale_x_discrete(labels = c("FIREFLY", "NTC", "RPL7", "RPL7mut", "RPS28", "RPS28mut"))

med_line <- try %>% mutate(Position_In_Z = (-(as.numeric(Pos_Z)) + 10000)/1000) %>% filter(gene == "FF") %>% summarize(median(Position_In_Z)) %>% as.numeric()

try %>% mutate(Position_In_Z = (-(as.numeric(Pos_Z)) + 10000)/1000) %>% filter(gene != "Lox", gene != "RPL8") %>% ggplot(aes(x = gene, y = Position_In_Z, fill = gene, alpha = gene)) + geom_violin() + geom_boxplot(width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = FALSE, col = FALSE, alpha = FALSE) + stat_compare_means(comparisons = list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("FF", "RPS28"), c("FF", "RPS28mut"), c("RPL7", "RPL7mut"), c("RPS28", "RPS28mut")), method = "wilcox.test", label.y = c(8.5,9.25,10,10.75,8,9.25)) + scale_fill_manual(values = c("#808080","#e8c040", "#e8c040", "#b82080", "#b82080")) + scale_alpha_manual(values = c(1,1,0.25,1,0.25)) + labs(x = "", y = "Position in Z (um)") + geom_hline(yintercept = med_line, size = 1, linetype = "dashed") + geom_hline(yintercept = 0) + coord_cartesian(ylim = c(-0.1,10.75)) + scale_x_discrete(labels = c("FIREFLY", "RPL7", "RPL7mut", "RPS28", "RPS28mut"))

```

# 5'TOP data (this is on the dish)

```{r, }
DISH <- list(c("20.12.17_RPDishFISH/Results/7d_FF_0S_01_#2_STACK__outline_spots_201220.txt" ,"S0", "FF", "01"),
c("20.12.17_RPDishFISH/Results/7d_FF_0S_02_#2_STACK__outline_spots_201220.txt" ,"S0", "FF", "02"),
c("20.12.17_RPDishFISH/Results/7d_FF_S6RF2_01_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "FF", "01"),
c("20.12.17_RPDishFISH/Results/7d_FF_S6RF2_02_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "FF", "02"),
c("20.12.17_RPDishFISH/Results/7d_FF_S8_01_#2_STACK__outline_spots_201220.txt" ,"S8", "FF", "01"),
c("20.12.17_RPDishFISH/Results/7d_FF_S8_02_#2_STACK__outline_spots_201220.txt" ,"S8", "FF", "02"),
c("20.12.17_RPDishFISH/Results/7d_lox_0S_01_#2_STACK__outline_spots_201220.txt" ,"S0", "Lox", "01"),
c("20.12.17_RPDishFISH/Results/7d_lox_0S_02_#2_STACK__outline_spots_201220.txt" ,"S0", "Lox", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPL7_0S_01_#2_STACK__outline_spots_201220.txt" ,"S0", "RPL7", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPL7_0S_02_#2_STACK__outline_spots_201220.txt" ,"S0", "RPL7", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPL7_S6RF2_02_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "RPL7", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPL7_S6RF2_03_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "RPL7", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPL7_S8_01_#2_STACK__outline_spots_201220.txt" ,"S8", "RPL7", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPL7_S8_02_#2_STACK__outline_spots_201220.txt" ,"S8", "RPL7", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPL7mut_0S_01_#2_STACK__outline_spots_201220.txt" ,"S0", "RPL7mut", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPL7mut_0S_02_#2_STACK__outline_spots_201220.txt" ,"S0", "RPL7mut", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPL7mut_S6RF2_01_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "RPL7mut", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPL7mut_S6RF2_02_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "RPL7mut", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPL7mut_S8_01_#2_STACK__outline_spots_201220.txt" ,"S8", "RPL7mut", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPL7mut_S8_02_#2_STACK__outline_spots_201220.txt" ,"S8", "RPL7mut", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPS28_0S_01_#2_STACK__outline_spots_201220.txt" ,"S0", "RPS28", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPS28_0S_02_#2_STACK__outline_spots_201220.txt" ,"S0", "RPS28", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPS28_S6RF2_01_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "RPS28", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPS28_S6RF2_02_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "RPS28", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPS28_S8_01_#2_STACK__outline_spots_201220.txt" ,"S8", "RPS28", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPS28_S8_02_#2_STACK__outline_spots_201220.txt" ,"S8", "RPS28", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPS28mut_0S_01_#2_STACK__outline_spots_201220.txt" ,"S0", "RPS28mut", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPS28mut_0S_02_#2_STACK__outline_spots_201220.txt" ,"S0", "RPS28mut", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPS28mut_S6RF2_01_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "RPS28mut", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPS28mut_S6RF2_02_#2_STACK__outline_spots_201220.txt" ,"S6RF2", "RPS28mut", "02"),
c("20.12.17_RPDishFISH/Results/7d_RPS28mut_S8_01_#2_STACK__outline_spots_201220.txt" ,"S8", "RPS28mut", "01"),
c("20.12.17_RPDishFISH/Results/7d_RPS28mut_S8_02_#2_STACK__outline_spots_201220.txt" ,"S8", "RPS28mut", "02"))
           

x <- c(1:length(DISH))
cell_file_list_DISH <- lapply(x, function(x){tidy_spot_files(unlist(DISH[x]))})
spots_DISH <- do.call(rbind, cell_file_list_DISH) 

spots_DISH_filt <- spots_DISH %>% filter(TH_fit == 1, as.numeric(INT_raw) > 850, as.numeric(INT_filt) > 850)


comparisons = list(c("FF", "RPL7"), c("RPL7", "RPL7mut"), c("FF", "RPS28"), c("RPS28", "RPS28mut"))

med_line <- bind_rows(spots_Dish_filt, spots_DISH_filt) %>% filter(gene == "FF", day != "S8", day != "S6RF2") %>% mutate(Position_In_Z = (as.numeric(Pos_Z) - 3000)/1000) %>% summarize(median(Position_In_Z)) %>% as.numeric()

bind_rows(spots_Dish_filt, spots_DISH_filt) %>% filter(gene %in% c("FF", "RPL7","RPL7mut"), day != "S8", day != "S6RF2") %>% mutate(Position_In_Z = (as.numeric(Pos_Z) - 3000)/1000)  %>% ggplot(aes(x = gene, y = Position_In_Z)) + geom_violin(aes(fill = gene, alpha = gene)) + geom_boxplot(aes(fill = gene, alpha = gene),width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = FALSE, col = FALSE, alpha = FALSE) + stat_compare_means(comparisons = list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("RPL7", "RPL7mut")), method = "wilcox.test", label.y = c(10,11,12))  + labs(x = "", y = "Position in Z(um)", title = "7d on dish") + geom_hline(yintercept = med_line, size = 1, linetype = "dashed") + geom_hline(yintercept = 0) +  scale_fill_manual(values = c("#808080", "#e8c040","#e8c040")) + scale_alpha_manual(values = c(1,1,0.5)) + labs(x = "", y = "Position in Z (um)") + coord_cartesian(ylim = c(-1,13))

```

```{r, alltogether}

a <- try %>% mutate(Position_In_Z = (-(as.numeric(Pos_Z)) + 10000)/1000) %>% filter(gene %in% c("FF", "RPL7", "RPL7mut")) %>% select(gene, Position_In_Z)
b <- bind_rows(spots_Dish_filt, spots_DISH_filt) %>% filter(gene %in% c("FF", "RPL7","RPL7mut"), day != "S8", day != "S6RF2") %>% mutate(Position_In_Z = (as.numeric(Pos_Z) - 3000)/1000) %>% select(gene, Position_In_Z)

a %>% ggplot(aes(x = gene, y = Position_In_Z)) + geom_violin(aes(fill = gene, alpha = gene)) + geom_boxplot(aes(fill = gene, alpha = gene),width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = FALSE, col = FALSE, alpha = FALSE) + stat_compare_means(comparisons = list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("RPL7", "RPL7mut")), method = "wilcox.test", label.y = c(10,11,12))  + labs(x = "", y = "Position in Z(um)", title = "7d on dish") + geom_hline(yintercept = med_line, size = 1, linetype = "dashed") + geom_hline(yintercept = 0) +  scale_fill_manual(values = c("#808080", "#e8c040","#e8c040")) + scale_alpha_manual(values = c(1,1,0.5)) + labs(x = "", y = "Position in Z (um)") + coord_cartesian(ylim = c(-1,13))

c <- spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-1000) / 1000)) %>% filter(line %in% c("pTL005", "RPL73TOPWT", "RPL73TOPmut")) %>%  mutate(gene = line, cell = substr(Cell, nchar(Cell), nchar(Cell))) %>% select(gene, Position_In_Z) %>% mutate(gene = ifelse(gene == "pTL005", "FF",gene))


c %>% ggplot(aes(x = line, y = Position_In_Z, fill = line)) + geom_violin(aes(alpha = line)) + geom_boxplot(aes(alpha = line), width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = FALSE, col = FALSE, alpha = FALSE) + stat_compare_means(comparisons = list(c("pTL005", "Net1UTR"), c("pTL005", "Net1peak"), c("pTL005", "RPL73TOPWT"), c("pTL005", "RPL73TOPmut"), c("Net1UTR", "Net1peak"), c("RPL73TOPWT", "RPL73TOPmut")), method = "wilcox.test", label.y = c(10,11,12,13,10,10)) + geom_hline(yintercept = med_line, size = 1, linetype = "dashed")  + scale_x_discrete(limits = c("pTL005", "Net1UTR", "Net1peak", "RPL73TOPWT", "RPL73TOPmut"), labels = c("Firefly", "Net1\nUTR", "Net1\npeak oligo", "3'TOP\nRPL7 WT", "3'TOP\nRPL7 mut")) + scale_fill_manual(values = c("#2c8bb0", "#2c8bb0", "#808080", "#ff8537", "#ff8537")) + scale_alpha_manual(values = c(0.5,1,1,0.5,1)) + labs(x = "", y = "Position in Z (um)") 


all_RPL7 <- bind_rows(list("Membrane" = a, "dish5TOP" = b, "dish3TOP" = c), .id = "exp")

med_line <- all_RPL7 %>% filter(gene == "FF") %>% summarize(median(Position_In_Z)) %>% as.numeric()

all_RPL7 %>% filter(exp != "Membrane") %>%  ggplot(aes(x = gene, y = Position_In_Z, fill = gene)) + geom_violin(aes(alpha = gene)) + geom_boxplot(aes(alpha = gene), width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = FALSE, col = FALSE, alpha = FALSE) + stat_compare_means(comparisons = list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("FF", "RPL73TOPWT"), c("FF", "RPL73TOPmut"), c("RPL7", "RPL7mut"), c("RPL73TOPWT", "RPL73TOPmut")), method = "wilcox.test") + geom_hline(yintercept = med_line, size = 1, linetype = "dashed")  + scale_x_discrete(limits = c("FF", "RPL7", "RPL7mut", "RPL73TOPWT", "RPL73TOPmut"), labels = c("Firefly", "5'TOP\nRPL7 WT", "5'TOP\nRPL7 mut", "3'TOP\nRPL7 WT", "3'TOP\nRPL7 mut")) + scale_fill_manual(values = c("#808080", "#ff8537", "#ff8537")) + scale_alpha_manual(values = c(0.5,1,1,0.5,1)) + labs(x = "", y = "Position in Z (um)") 

``` 



