---
title: "22.03.10_C2bbe1drugs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(ggpubr)
```

## 7 Day differentiated C2bbe1 pTL005 and Net1 3'UTR cells on dishes with Kinesin or Dynein inhibitors
## K0.5 = 25uM Kinesore and K1.0 = 50uM Kinesore
## Round 1

```{r,}
spots <- as_tibble(read.csv("/Users/raegoering/Documents/TaliaferroLab/IEC_FISH/22.03.10_C2bbe1drugs/Results/_FISH-QUANT__all_spots_220310.txt", header = TRUE, sep = "\t", skip = 13))

spots <- spots %>% separate(File, into = c("C2bbe1", "7d", "line", "drug", "image", "Stack"), sep = "_") %>% mutate(image = substr(image, 1, 2)) %>% select(-C2bbe1, -`7d`, -Stack) %>% filter(drug != "K1.0", drug != "K1.0D")



```

```{r, }

## INT_raw
spots %>% filter(TH_fit == 1) %>% select(line,INT_raw) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(300,1800) + geom_hline(yintercept = 950)

## INT_filt
spots %>% filter(TH_fit == 1) %>% select(line,INT_filt) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(0,1000) + geom_hline(yintercept = 400)

#BGD
spots %>% filter(TH_fit == 1) %>% select(line,BGD) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(200,600) + geom_hline(yintercept = 375)

#PosZ
spots %>% filter(TH_fit == 1) %>% select(line,Pos_Z) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + geom_hline(yintercept = c(1000,10000))

#really limits spots.
spots_filt <- spots %>% filter(TH_fit == 1, as.numeric(INT_raw) > 950, as.numeric(BGD) < 375, as.numeric(SigmaZ) < 700)

#are all images similar?

spots_filt %>%  filter(line != "Lox") %>% ggplot(aes(x = Cell, y = as.numeric(Pos_Z), color = image)) + geom_boxplot(position = "dodge") + facet_grid(line~drug) 

spots_filt <- spots_filt %>% filter(!(line == "FF" & drug == "D" & image == "03"),
                                    !(line == "FF" & drug == "K0.5" & image == "01"))

spots_filt %>% filter(line != "Lox") %>% ggplot(aes(x = as.numeric(INT_raw), y = as.numeric(Pos_Z))) + geom_density2d() + facet_grid(line~drug)


```

```{r, }

comps <- list(c("DMSO", "D"), c("DMSO", "K0.5"), c("DMSO", "K0.5D"), c("K0.5", "K0.5D"))

spots_filt %>% group_by(line, drug, image, Cell) %>% summarise(num_spots = n()) %>% ggplot(aes(x = drug, y = num_spots)) + geom_boxplot(aes(fill = line)) + theme_cowplot() + guides(fill = "none", col = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label = "p.signif", hide.ns = TRUE, size = 7, vjust = 0.5) + labs(x = "", y = "Number of spots per cell") + EnvStats::stat_n_text() + facet_wrap(.~line) 

med_line <- spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line == "FF",drug == "DMSO") %>% summarize(median(Position_In_Z)) %>% as.numeric()

spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x = drug, y = Position_In_Z-med_line, fill = line)) + geom_violin() + geom_boxplot(aes(alpha = line), width = 0.25, outlier.shape = NA) + theme_cowplot() + guides(fill = "none", col = "none", alpha = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label.y = c(4,4.5,3.5,5,5.5,4.5), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#808080", "#95e7d9")) + labs(x = "", y = "Position in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-4,6.5)) + facet_wrap(.~line)

comps <- list(c("DMSO", "Dynein\nInhibitor"),c("DMSO", "Kinesin\nInhibitor"))

spots_filt %>% filter(drug != "K1.0" , drug != "K1.0D", drug != "K0.5D") %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x =  factor(drug,levels = c("DMSO", "D", "K0.5"), labels= c("DMSO","Dynein\nInhibitor","Kinesin\nInhibitor")), y = Position_In_Z-med_line)) + geom_violin(aes(fill = line)) + geom_boxplot(aes(fill = line),width = 0.25, outlier.shape = NA)  + theme_cowplot() + guides(fill = "none", col = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label.y = c(4,4.5), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#808080", "#95e7d9")) + labs(x = "", y = "Position in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-2.75,5.)) + facet_wrap(.~line)

comps <- list(c("FF", "Net1"))

spots_filt %>% filter(drug != "K1.0" , drug != "K1.0D", drug != "K0.5D") %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x =  line, y = Position_In_Z-med_line)) + geom_violin(aes(fill = line)) + geom_boxplot(aes(fill = line),width = 0.25, outlier.shape = NA)  + theme_cowplot() + guides(fill = "none", col = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label.y = c(4,4.5), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#808080", "#95e7d9")) + labs(x = "", y = "Position in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-2.75,5.)) + facet_wrap(.~factor(drug,levels = c("DMSO", "D", "K0.5"), labels= c("DMSO","Dynein\nInhibitor","Kinesin\nInhibitor")))

```

```{r, }
spots_filt %>% filter(line == "FF", drug != "K1.0" , drug != "K1.0D", drug != "K0.5D") %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x =  factor(drug,levels = c("DMSO", "D", "K0.5"), labels= c("DMSO","Dynein\nInhibitor","Kinesin\nInhibitor")), y = Position_In_Z-med_line)) + geom_violin(aes(fill = line)) + geom_boxplot(aes(fill = line),width = 0.25, outlier.shape = NA)  + theme_cowplot() + guides(fill = "none", col = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label.y = c(4,4.5), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#808080")) + labs(x = "", y = "Firefly Reporter Transcript\nPosition in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-2.75,5.)) 

spots_filt %>% filter(line == "Net1", drug != "K1.0" , drug != "K1.0D", drug != "K0.5D") %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x =  factor(drug,levels = c("DMSO", "D", "K0.5"), labels= c("DMSO","Dynein\nInhibitor","Kinesin\nInhibitor")), y = Position_In_Z-med_line)) + geom_violin(aes(fill = line)) + geom_boxplot(aes(fill = line),width = 0.25, outlier.shape = NA)  + theme_cowplot() + guides(fill = "none", col = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label.y = c(4,4.5), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#95e7d9")) + labs(x = "", y = "Net1 3'UTR Reporter Transcript\nPosition in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-2.75,5.))
```



## 7 Day differentiated C2bbe1 pTL005 and RP 5'TOP cells on dishes with Kinesin or Dynein inhibitors
## K = 25uM Kinesore and D = ciliobrevinA
## Round 1

```{r,}
spotsRP <- as_tibble(read.csv("/Users/raegoering/Documents/TaliaferroLab/IEC_FISH/22.04.07_C2bbe1RPdrug/Results/_FISH-QUANT__all_spots_220407.txt", header = TRUE, sep = "\t", skip = 13))

spotsRP2 <- as_tibble(read.csv("/Users/raegoering/Documents/TaliaferroLab/IEC_FISH/22.04.07_C2bbe1RPdrug/Results/_FISH-QUANT__all_spots_220411.txt", header = TRUE, sep = "\t", skip = 13))

spotsRP <- rbind(spotsRP, spotsRP2) %>% separate(File, into = c("C2bbe1", "7d", "line", "drug", "image", "Stack"), sep = "_") %>% mutate(image = substr(image, 1, 2)) %>% select(-C2bbe1, -`7d`, -Stack)



```

```{r, }

## INT_raw
spotsRP %>% filter(TH_fit == 1) %>% select(line,INT_raw) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(300,1800) + geom_hline(yintercept = 950)

## INT_filt
spotsRP %>% filter(TH_fit == 1) %>% select(line,INT_filt) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(0,1000) + geom_hline(yintercept = 300)

#BGD
spotsRP %>% filter(TH_fit == 1) %>% select(line,BGD) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(200,600) + geom_hline(yintercept = 375)

#PosZ
spotsRP %>% filter(TH_fit == 1) %>% select(line,Pos_Z) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + geom_hline(yintercept = c(1000,12000))

#really limits spots.
spotsRP_filt <- spotsRP %>% filter(TH_fit == 1, as.numeric(INT_raw) > 950, as.numeric(INT_raw) < 2500, as.numeric(BGD) > 375,as.numeric(BGD) < 550, as.numeric(SigmaZ) < 700, as.numeric(Pos_Z) < 12000, as.numeric(Pos_Z) > 1000)

#are all images similar?

spotsRP_filt %>%  filter(line != "Lox") %>% ggplot(aes(x = Cell, y = as.numeric(Pos_Z), color = image)) + geom_boxplot(position = "dodge") + facet_grid(line~factor(drug, levels = c("DMSO","K","D"))) 

spotsRP_filt <- spotsRP_filt %>% filter(!(line == "FF" & drug == "DMSO" & image == "02" & Cell %in% c("Cell_1","Cell_6", "Cell_7")),
                                        !(line == "RPL7" & drug == "DMSO" & image == "02"),
                                        !(line == "RPL7mut" & drug == "DMSO" & image %in% c("01","03")),
                                        !(line == "RPL7" & drug == "D" & image %in% c("01","03")),
                                        !(line == "RPS28" & drug == "D" & image == "01"),
                                        !(line == "RPS28" & drug == "D" & image == "02" & Cell %in% c("Cell_1", "Cell_2")),
                                        !(line == "RPS28" & drug == "D" & image == "03" & Cell %in% c("Cell_3", "Cell_4", "Cell_7")),
                                        !(line == "RPS28" & drug == "D" & image == "04" & Cell %in% c("Cell_3")),
                                        !(line == "RPS28" & drug == "D" & image == "05" & Cell %in% c("Cell_3", "Cell_5")),
                                        !(line == "RPS28" & drug == "D" & image == "06" & Cell %in% c("Cell_1")),
                                        !(line == "RPS28mut" & drug == "D" & image == "03"),
                                        !(line == "RPS28mut" & drug == "D" & image == "02" & Cell %in% c("Cell_3", "Cell_4", "Cell_5")),
                                        !(line == "RPL7" & drug == "K" & image %in% c("02","03")),
                                        !(line == "RPL7" & drug == "K" & image == "01" & Cell %in% c("Cell_1", "Cell_4")),
                                        !(line == "RPL7mut" & drug == "K" & image == "02"))

spotsRP_filt %>% filter(line != "Lox") %>% ggplot(aes(x = as.numeric(INT_raw), y = as.numeric(Pos_Z))) + geom_density2d() + facet_grid(line~factor(drug, levels = c("DMSO","K","D"))) 


```



```{r, }

comps <- list(c("DMSO", "K"), c("DMSO", "D"), c("K", "D"))

spotsRP_filt %>% group_by(line, drug, image, Cell) %>% summarise(num_spots = n()) %>% ggplot(aes(x = drug, y = num_spots)) + geom_boxplot(aes(fill = line, alpha = line)) + theme_cowplot() + guides(fill = "none", col = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label = "p.signif", hide.ns = TRUE, size = 7, vjust = 0.5) + labs(x = "", y = "Number of spots per cell") + EnvStats::stat_n_text() + facet_wrap(.~line) + scale_fill_manual(values = c("#808080", "#808080","#e8c040", "#e8c040", "#b82080", "#b82080")) + scale_alpha_manual(values = c(1,1,1,0.5,1,0.5))

comps <- list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("RPL7", "RPL7mut"),c("FF", "RPS28"), c("FF", "RPS28mut"), c("RPS28", "RPS28mut"))

spotsRP_filt %>% group_by(line, drug, image, Cell) %>% summarise(num_spots = n()) %>% ggplot(aes(x = line, y = num_spots)) + geom_boxplot(aes(fill = line, alpha = line)) + theme_cowplot() + guides(fill = "none", col = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label = "p.signif", hide.ns = TRUE, size = 7, vjust = 0.5) + labs(x = "", y = "Number of spots per cell") + EnvStats::stat_n_text() + facet_wrap(.~factor(drug, levels = c("DMSO","K","D"))) + scale_fill_manual(values = c("#808080", "#808080","#e8c040", "#e8c040", "#b82080", "#b82080")) + scale_alpha_manual(values = c(1,1,1,0.5,1,0.5))

```


```{r, }
med_line <- spotsRP_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line == "FF",drug == "DMSO") %>% summarize(median(Position_In_Z)) %>% as.numeric()

comps <- list(c("FF", "RPL7"), c("RPL7", "RPL7mut"),c("FF", "RPS28"), c("RPS28", "RPS28mut"))

spotsRP_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x = line, y = Position_In_Z-med_line)) + geom_violin(aes(fill = line, alpha = line)) + geom_boxplot(aes(fill = line, alpha = line), width = 0.25, outlier.shape = NA) + theme_cowplot() + guides(fill = "none", col = "none", alpha = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label.y = c(5,4,6,4), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#808080","#e8c040", "#e8c040", "#b82080", "#b82080")) + scale_alpha_manual(values = c(1,1,0.5,1,0.5)) + labs(x = "", y = "Position in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-4,7)) + facet_wrap(.~factor(drug, levels = c("DMSO","D","K"), labels = c("DMSO", "Dynein\nInhibitor", "Kinesin\nInhibitor"))) + theme(strip.background = element_rect(color = "white", fill = "white")) + EnvStats::stat_n_text(y.pos = -10)

comps <- list(c("DMSO", "D"), c("K", "D"), c("DMSO", "K"))

RPmedlines <- spotsRP_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox", drug == "DMSO") %>% group_by(line) %>% summarize(hline = median(Position_In_Z)-med_line) 

spotsRP_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x = drug, y = Position_In_Z-med_line)) + geom_violin(aes(fill = line, alpha = line)) + geom_boxplot(aes(fill = line, alpha = line), width = 0.25, outlier.shape = NA) + theme_cowplot() + guides(fill = "none", col = "none", alpha = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label.y = c(3.5,4.25,5.5), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(aes(yintercept = hline), data = RPmedlines, size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#808080","#e8c040", "#e8c040", "#b82080", "#b82080")) + scale_alpha_manual(values = c(1,1,0.5,1,0.5)) + labs(x = "", y = "Position in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-4,7)) + facet_wrap(.~line) + scale_x_discrete(limits = c("DMSO", "D", "K"), labels = c("DMSO", "Dynein\nInhibitor", "Kinesin\nInhibitor")) + theme(strip.background = element_rect(color = "white", fill = "white")) + EnvStats::stat_n_text(y.pos = -10)

spotsRP_filt %>% filter(line %in% c("RPL7", "RPS28")) %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x = drug, y = Position_In_Z-med_line)) + geom_violin(aes(fill = line, alpha = line)) + geom_boxplot(aes(fill = line, alpha = line), width = 0.25, outlier.shape = NA) + theme_cowplot() + guides(fill = "none", col = "none", alpha = "none") + stat_compare_means(comparisons = comps, method = "wilcox.test", label.y = c(3.5,4.25,5.5), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(aes(yintercept = hline), data = filter(RPmedlines, line %in% c("RPL7","RPS28")), size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#e8c040", "#b82080")) + scale_alpha_manual(values = c(1,1)) + labs(x = "", y = "Position in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-4,7)) + facet_wrap(.~line) + scale_x_discrete(limits = c("DMSO", "D", "K"), labels = c("DMSO", "Dynein\nInhibitor", "Kinesin\nInhibitor")) + theme(strip.background = element_rect(color = "white", fill = "white")) + EnvStats::stat_n_text(y.pos = -10)



```

#even simpler plots

```{r, }

RPmedlines <- spotsRP_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox", drug == "DMSO") %>% group_by(line) %>% summarize(hline = median(Position_In_Z)-med_line) 

spotsRP_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line %in% c("RPL7","RPS28"), drug != "D") %>% ggplot(aes(x = drug, y = Position_In_Z-med_line)) + geom_violin(aes(fill = line, alpha = line)) + geom_boxplot(aes(fill = line, alpha = line), width = 0.25, outlier.shape = NA) + theme_cowplot() + guides(fill = "none", col = "none", alpha = "none") + stat_compare_means(comparisons = list(c("DMSO", "K")), method = "wilcox.test", label.y = 5.5, label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(aes(yintercept = hline), data = filter(RPmedlines, line %in% c("RPL7","RPS28")), size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#e8c040", "#b82080")) + scale_alpha_manual(values = c(1,1)) + labs(x = "", y = "Position in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-3.5,7)) + facet_wrap(.~line) + scale_x_discrete(limits = c("DMSO","K"), labels = c("DMSO", "Kinesin\nInhibitor")) + theme(strip.background = element_rect(color = "white", fill = "white")) + EnvStats::stat_n_text(y.pos = -10)

```
