---
title: "LARP1RescueStarve"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(ggpubr)

```

## 7 Day differentiated C2bbe1 LARP1 KO G10 cells on dishes with LARP1 rescue constructs
### Starved for 6 hours then refed for 2 or continued starvation for 2 more hours

```{r,  read in spots}
spots <- as_tibble(read.csv("/Users/raegoering/Documents/TaliaferroLab/IEC_FISH/22.03.04_LARPRescueStarve/Results/_FISH-QUANT__all_spots_220305.txt", header = TRUE, sep = "\t", skip = 13))

spots <- spots %>% separate(File, into = c("C2bbe1", "7d", "LARP1KO", "G10", "state", "line", "rescue", "image", "Stack"), sep = "_") %>% mutate(image = substr(image, 1, 2)) %>% select(-C2bbe1, -`7d`, -LARP1KO, -G10, -Stack) %>% mutate(state = ifelse(state == "8S", "fasting", "refed"))

```

```{r, thresholdmyself}

## INT_raw
spots %>% filter(TH_fit == 1) %>% select(line,INT_raw) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(300,2500) + geom_hline(yintercept = 750)

#BGD
spots %>% filter(TH_fit == 1) %>% select(line,BGD) %>% gather(-line,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = line, fill = line)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(150,650) + geom_hline(yintercept = 375)

#really limits spots.
spots_filt <- spots %>% filter(TH_fit == 1, as.numeric(INT_raw) > 900, as.numeric(INT_raw) < 3000, as.numeric(SigmaZ) < 1000, as.numeric(BGD) < 375)

#are all images similar?

spots_filt %>%  filter(line != "Lox", state == "refed") %>% ggplot(aes(x = Cell, y = as.numeric(Pos_Z), color = image)) + geom_boxplot(position = "dodge") + facet_grid(rescue~line) 

spots_filt %>%  filter(line != "Lox", state == "fasting") %>% ggplot(aes(x = Cell, y = as.numeric(Pos_Z), color = image)) + geom_boxplot(position = "dodge") + facet_grid(rescue~line) 

spots_filt <- spots_filt %>% filter(!(line == "RPS28" & rescue == "GFP" & state == "fasting" & image == "03"), !(line == "RPS28" & rescue == "LARP1" & state == "fasting" & image == "03" & Cell == "Cell_2"),  !(line == "RPS28" & rescue == "LARP1" & state == "fasting" & image == "01" & Cell == "Cell_3"))

spots_filt %>% filter(line != "Lox") %>% ggplot(aes(x = as.numeric(INT_raw), y = as.numeric(Pos_Z))) + geom_density2d() + facet_grid(rescue~line)

```



```{r, spot_analysis}

comparisons <- list(c("LARP1\nfasting","LARP1\nrefed"), c("GFP\nfasting","GFP\nrefed"))

spots_filt %>% mutate(rescuestate = paste(rescue,state,sep = "\n")) %>% group_by(line,state,rescuestate, image, rescue, Cell) %>% summarise(num_spots = n()) %>% ggplot(aes(x = rescuestate, y = num_spots)) + geom_boxplot(aes(fill = line)) + theme_cowplot() + guides(fill = "none", col = "none") + stat_compare_means(comparisons = comparisons, method = "wilcox.test", label.y = 225, label = "p.signif", hide.ns = TRUE, size = 7, vjust = 0.5) + labs(x = "", y = "Number of spots per cell") + EnvStats::stat_n_text() + facet_wrap(.~line) + scale_x_discrete(limits = c("LARP1\nfasting","LARP1\nrefed", "GFP\nfasting","GFP\nrefed"))
                      

# FF image1, RPL7 image3


med_line <- spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line == "FF",rescue == "LARP1", state == "fasting") %>% summarize(median(Position_In_Z)) %>% as.numeric()

spots_filt %>% mutate(rescuestate = paste(rescue,state,sep = "\n")) %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000)) %>% filter(line != "Lox") %>% ggplot(aes(x = rescuestate, y = Position_In_Z-med_line, fill = line)) + geom_violin(aes(alpha = line)) + geom_boxplot(aes(alpha = line), width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = "none", col = "none", alpha = "none") + stat_compare_means(comparisons = comparisons, method = "wilcox.test", label.y = c(4,4.5,5,4), label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed")  + scale_fill_manual(values = c("#808080", "#e8c040", "#e8c040", "#b82080", "#b82080")) + scale_alpha_manual(values = c(1,1,0.5,1,0.5)) + labs(x = "", y = "Position in Z (um)\nFirefly Normalized") + coord_cartesian(ylim = c(-3,6)) + facet_wrap(.~line) + scale_x_discrete(limits = c("LARP1\nfasting","LARP1\nrefed", "GFP\nfasting","GFP\nrefed"))


comparisons <- list(c("FF", "RPL7"), c("FF", "RPS28"), c("RPL7", "RPL7mut"), c("RPS28", "RPS28mut"))

LARP1medline <- spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000), rescuestate = paste(rescue,state,sep = "\n")) %>% filter(line == "FF") %>% group_by(rescuestate) %>% summarize(meds = median(Position_In_Z-med_line))

spots_filt %>% mutate(Position_In_Z = ((as.numeric(Pos_Z)-2500) / 1000), rescuestate = paste(rescue,state,sep = "\n")) %>% filter(line != "Lox") %>% ggplot(aes(x = line, y = Position_In_Z-med_line)) + geom_violin(aes(fill = line,alpha = line)) + geom_boxplot(aes(fill = line, alpha = line), width = 0.25, outlier.shape = NA) + geom_point(alpha = 0.001, position = "jitter") + theme_cowplot() + guides(fill = "none", col = "none", alpha = "none") + stat_compare_means(comparisons = comparisons, method = "wilcox.test", label.y = 4, label = "p.signif", size = 7, vjust = 0.5, hide.ns = TRUE) + geom_hline(aes(yintercept = meds), data = LARP1medline, size = 1, linetype = "dashed") + scale_fill_manual(values = c("#808080", "#e8c040", "#e8c040", "#b82080", "#b82080")) + scale_alpha_manual(values = c(1,1,0.5,1,0.5))  + labs(x = "", y = "Position in Z (um)/nFirefly Normalized") + coord_cartesian(ylim = c(-3,6)) + facet_wrap(.~rescuestate) 

```

