---
title: "CAD_Net1_FISH"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(cowplot)
```

## Round 1 +2!
### Net1 expressing CADs were dox induced 


```{r, all spot tidy data}
all_spot_net1 <- as_tibble(read.csv("/Users/raegoering/Documents/TaliaferroLab/IEC_FISH/21.10.18_CAD_Net1/Results/_FISH-QUANT__all_spots_211018.txt", header = TRUE, skip = 13, sep = "\t")) %>% mutate(day = "1")

all_spot_net2 <- as_tibble(read.csv("/Users/raegoering/Documents/TaliaferroLab/IEC_FISH/21.10.18_CAD_Net1/Results/_FISH-QUANT__all_spots_211019.txt", header = TRUE, skip = 13, sep = "\t")) %>% mutate(day = "2")

all_spot_net <- rbind(all_spot_net1, all_spot_net2) %>% separate(File, into = c("CAD", "Net1", "gene", "image","stack"), sep = "_") %>%  mutate(cell = as.numeric(substr(Cell, 6, 6)), cell = ifelse(cell %% 2 == 0, "neurite", "soma"), image = substr(image,1,2)) %>% select(gene, image, cell,day, everything(), -stack) 

```

```{r, all spot filter}
##a closer look with each condition.
all_spot_net %>% select(gene,, cell,INT_raw) %>% gather(-gene,,-cell, key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = gene, fill = gene)) + geom_density(alpha = 0.5) + theme_cowplot() + ylim(1000,3500) + facet_grid(.~cell) + geom_hline(yintercept = 1500)

all_spot_net %>% select(gene,cell,BGD) %>% gather(-gene,,-cell, key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = gene, fill = gene)) + geom_density(alpha =0.5) + theme_cowplot() + ylim(200,900) + facet_grid(.~cell) + geom_hline(yintercept = 650)

all_spot_net %>% select(gene,cell,SigmaX) %>% gather(-gene,,-cell,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = gene, fill = gene)) + geom_density(alpha = 0.5) + theme_cowplot()  + facet_grid(.~cell) + geom_hline(yintercept = 200)

all_spot_net %>% select(gene,cell,SigmaZ) %>% gather(-gene,,-cell,key = "param", value = "value") %>% mutate(value = as.numeric(value)) %>% ggplot(aes(y=value, group = gene, fill = gene)) + geom_density(alpha = 0.5) + theme_cowplot() + facet_grid(.~cell) + geom_hline(yintercept = 500)


#really limits spots.
net_filt <- all_spot_net %>% filter(TH_fit == 1, as.numeric(INT_raw) > 1500, as.numeric(INT_raw) < 4000, as.numeric(BGD) < 650) #, as.numeric(Pos_Z) > 450, as.numeric(Pos_Z) < 10000)
```


```{r, }
p <- net_filt %>% mutate(Cell =as.numeric(substr(Cell,6,6)), Cell = ifelse(Cell %%2 == 0, Cell-1,Cell)) %>%  group_by(gene,image,cell,Cell,day) %>% summarize(numspots = n()) 

p <- rbind(p, tibble(gene = c("deletion","deletion","deletion","deletion","FF","FF","FF"),
       image = c("01","03","05","06","01","01","03"),
       cell = c("neurite","neurite","neurite","neurite","neurite","neurite","neurite"),
       Cell = c(3,1,3,3,1,1,1),
       day = c("1","1","1","1","1","2","1"),
       numspots = c(0,0,0,0,0,0,0))) %>% 
  filter(!(gene == "UTR" & image == "03" & day == "1" & Cell == 1),
         !(gene == "UTR" & image == "03" & day == "2" & Cell == 1),
         !(gene == "UTR" & image == "02" & day == "2" & Cell == 1))

p %>% ggplot(aes(x = gene, y = numspots, fill = gene)) + geom_boxplot(outlier.shape = NA) + theme_cowplot() + facet_grid(.~cell) + EnvStats::stat_n_text(y.pos = -10) + labs(x= "", y = "Total Number of\nReporter Transcripts") + guides(fill = "none") + scale_fill_manual(values = c("#51707c","#808080", "#6ab6b0", "#95e7d9")) + scale_x_discrete(limits = c("FF", "UTR", "Peak", "deletion"), labels = c("Firefly", "Net1\n3'UTR", "Net1\nLE", "Net1\n3'UTR ΔLE")) + theme(strip.background = element_rect(color = "white", fill = "white")) + theme(text = element_text(size=15)) 

net_filt %>% mutate(Cell =as.numeric(substr(Cell,6,6)), Cell = ifelse(Cell %%2 == 0, Cell-1,Cell)) %>%  group_by(gene,image,cell,Cell,day) %>% summarize(numspots = n()) %>% spread(cell,numspots) %>% mutate(totspots = neurite + soma) %>% ggplot(aes(x = gene, y = totspots, fill = gene)) + geom_boxplot() + theme_cowplot() + theme_cowplot() + stat_compare_means(comparisons = list(c("FF", "UTR"), c("FF", "Peak"),c("FF", "deletion")), method = "wilcox.test") + ylab("Total Spots") + guides(fill = FALSE) + scale_x_discrete(limits = c("FF", "UTR", "Peak", "deletion")) + EnvStats::stat_n_text(y.pos = -50)

net_filt %>% mutate(Cell =as.numeric(substr(Cell,6,6)), Cell = ifelse(Cell %%2 == 0, Cell-1,Cell)) %>%  group_by(gene,image,cell,Cell,day) %>% summarize(numspots = n()) %>% filter(cell == "soma") %>% ggplot(aes(x = gene, y = numspots)) + geom_violin(aes(fill = gene)) + geom_boxplot(aes(fill = gene), outlier.shape = NA, width = 0.2) + theme_cowplot() + stat_compare_means(comparisons = list(c("FF", "UTR"), c("FF", "Peak"),c("FF", "deletion")), method = "wilcox.test") + labs(x = "", y = "Spots in Neurite") + guides(fill = FALSE) + scale_fill_manual(values = c("#808080","#51707c", "#6ab6b0", "#95e7d9")) + scale_x_discrete(limits = c("FF", "UTR", "Peak", "deletion")) + EnvStats::stat_n_text(y.pos = -5)


net_filt_summary <- net_filt %>% 
  group_by(gene,image,cell,Cell,day) %>% summarize(N_thres_Total = n()) %>% ungroup() %>% select(gene, image, cell,Cell,day, N_thres_Total)  %>% 
  mutate(Cell =as.numeric(substr(Cell,6,6)), Cell = ifelse(Cell %%2 == 0, Cell-1,Cell)) %>% 
  group_by(gene,image,Cell,day) %>% 
  spread(key = cell, value = N_thres_Total) %>%
  mutate(neurite = ifelse(is.na(neurite), 0, neurite)) %>% 
  mutate(n_s_thresh = neurite/soma) %>% 
  select(gene, image,day, n_s_thresh) %>% 
  ungroup() %>% left_join(., net_filt %>% group_by(gene,image,cell,Cell,day) %>% summarize(N_thres_Total = n()) %>% ungroup() %>% select(gene,day, image, cell, N_thres_Total)) 

net_filt_summary %>% filter(cell == "soma", n_s_thresh < 2) %>% select(-N_thres_Total) %>% unique()  %>% ggplot(aes(x = gene, y = n_s_thresh)) + geom_boxplot(aes(fill = gene),outlier.shape = NA) + theme_cowplot() + stat_compare_means(comparisons = list(c("FF", "UTR"), c("FF", "Peak"),c("FF", "deletion"), c("UTR", "Peak"), c("UTR", "deletion")), method = "wilcox.test", label.y = c(1,1.1,1.2,0.8,0.9), label = "p.signif", size = 7, hide.ns = TRUE, vjust = 0.5) + labs(x = "", y = "Reporter Transcripts\nin Neurite/Soma") + guides(fill = FALSE)  + scale_fill_manual(values = c("#51707c","#808080", "#6ab6b0", "#95e7d9")) + scale_x_discrete(limits = c("FF", "UTR", "Peak", "deletion"), labels = c("Firefly", "Net1\n3'UTR", "Net1\nLE", "Net1\n3'UTR ΔLE")) + EnvStats::stat_n_text(y.pos = -0.05) + coord_cartesian(ylim=c(-0.07,1.4))

```

